// Generated by CoffeeScript 1.3.3
(function() {
  var inject, injectContent, xhr;

  inject = function(name, callback) {
    var s;
    s = document.createElement('script');
    s.src = chrome.extension.getURL('js/' + name);
    s.onload = callback || function() {};
    return document.head.appendChild(s);
  };

  injectContent = function(content) {
    var s;
    s = document.createElement('script');
    s.type = 'text/webworker';
    s.textContent = content;
    s.id = 'chrome-auto-group-worker-content';
    return document.body.appendChild(s);
  };

  inject('underscore-min.js', function() {
    return inject('auto_group.js');
  });

  xhr = new XMLHttpRequest;

  xhr.onreadystatechange = function() {
    if (xhr.readyState === 4 && xhr.status === 200) {
      return injectContent(xhr.responseText);
    }
  };

  xhr.open('GET', chrome.extension.getURL('js/calculate.js'), true);

  xhr.send(null);

}).call(this);
