// Generated by CoffeeScript 1.4.0
(function() {
  var inject;

  inject = function(name, callback) {
    var s;
    s = document.createElement('script');
    s.src = chrome.extension.getURL('js/' + name);
    s.onload = callback || function() {};
    return document.head.appendChild(s);
  };

  inject('underscore-min.js', function() {
    return inject('auto_group.js');
  });

}).call(this);
